const products = [
  {id:"blanket",name:"Електроковдра HYGGE",meta:"120×160 см, 3 режими",category:"Тепло",price:2299,imageClass:"sprite-0"},
  {id:"lantern",name:"Ліхтар аварійний LUMEN 300",meta:"До 24 годин роботи",category:"Світло",price:1299,imageClass:"sprite-1"},
  {id:"mini-ups",name:"Mini UPS DC 10400",meta:"10400 mAh, 18W",category:"Енергія",price:3499,imageClass:"sprite-2"},
  {id:"powerbank",name:"Павербанк 20 000 mAh",meta:"2×USB, USB‑C, 22.5W",category:"Енергія",price:1199,imageClass:"sprite-3"},
  {id:"bulb",name:"Аварійна лампочка LED 12W",meta:"E27, 3 режими",category:"Світло",price:299,imageClass:"sprite-4"},
  {id:"hand-warmer",name:"USB‑грілка для рук",meta:"5000 mAh, 3 режими",category:"Тепло",price:799,imageClass:"sprite-5"},
  {id:"set-warm",name:"Набір «Теплий вечір»",meta:"Електроплед, ліхтар, павербанк",category:"Набір",price:2999,imageClass:"sprite-0"},
  {id:"set-light",name:"Набір «Світло в квартирі»",meta:"Лампочки, ліхтар, павербанк",category:"Набір",price:2699,imageClass:"sprite-1"},
  {id:"set-wifi",name:"Набір «Wi‑Fi завжди»",meta:"Mini UPS, роутер, павербанк",category:"Набір",price:3399,imageClass:"sprite-2"},
  {id:"set-max",name:"Набір «ХАТА.ON MAX»",meta:"Максимальна автономність",category:"Набір",price:5499,imageClass:"sprite-2"}
];
const formatPrice=value=>`${new Intl.NumberFormat("uk-UA").format(value)} ₴`;
const productMap=new Map(products.map(product=>[product.id,product]));
const productGrid=document.querySelector("#product-grid"),cartDrawer=document.querySelector("#cart-drawer"),drawerBackdrop=document.querySelector("#drawer-backdrop"),cartItems=document.querySelector("#cart-items"),cartEmpty=document.querySelector("#cart-empty"),cartFooter=document.querySelector("#cart-footer"),cartCount=document.querySelector("#cart-count"),cartTotal=document.querySelector("#cart-total"),checkoutDialog=document.querySelector("#checkout-dialog"),resultDialog=document.querySelector("#result-dialog"),toast=document.querySelector("#toast");
let cart=loadCart(),preparedOrder="";
function loadCart(){try{const saved=JSON.parse(localStorage.getItem("hata-on-cart")||"{}");return Object.fromEntries(Object.entries(saved).filter(([id,quantity])=>productMap.has(id)&&quantity>0));}catch{return {};}}
function saveCart(){localStorage.setItem("hata-on-cart",JSON.stringify(cart));}
function renderProducts(){productGrid.innerHTML=products.filter(product=>product.category!=="Набір").map(product=>`<article class="product-card"><button class="favorite" type="button" aria-label="Додати ${product.name} в обране">♡</button><div class="product-visual sprite ${product.imageClass}"></div><div class="product-info"><h3>${product.name}</h3><p>${product.meta}</p><div><b>${formatPrice(product.price)}</b><button class="mini-cart" type="button" data-add-product="${product.id}" aria-label="Додати ${product.name} у кошик">▱</button></div></div></article>`).join("");}
function addToCart(id){cart[id]=(cart[id]||0)+1;saveCart();renderCart();showToast("Додано у кошик");}
function updateQuantity(id,delta){if(!cart[id])return;cart[id]+=delta;if(cart[id]<=0)delete cart[id];saveCart();renderCart();}
function renderCart(){const entries=Object.entries(cart),quantity=entries.reduce((sum,[,count])=>sum+count,0),total=entries.reduce((sum,[id,count])=>sum+productMap.get(id).price*count,0);cartCount.textContent=quantity;cartEmpty.hidden=entries.length>0;cartFooter.hidden=entries.length===0;cartTotal.textContent=formatPrice(total);cartItems.innerHTML=entries.map(([id,count])=>{const product=productMap.get(id);return `<div class="cart-item"><div class="cart-thumb sprite ${product.imageClass}"></div><div><h3>${product.name}</h3><b>${formatPrice(product.price*count)}</b><div class="quantity"><button type="button" data-cart-change="-1" data-product-id="${id}">−</button><span>${count}</span><button type="button" data-cart-change="1" data-product-id="${id}">+</button></div></div><button class="remove-item" type="button" data-remove-product="${id}">Видалити</button></div>`;}).join("");}
function openCart(){cartDrawer.classList.add("open");cartDrawer.setAttribute("aria-hidden","false");drawerBackdrop.hidden=false;document.body.classList.add("no-scroll");}
function closeCart(){cartDrawer.classList.remove("open");cartDrawer.setAttribute("aria-hidden","true");drawerBackdrop.hidden=true;document.body.classList.remove("no-scroll");}
function showToast(message){toast.textContent=message;toast.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove("show"),1800);}
function cartSummary(){const lines=Object.entries(cart).map(([id,count])=>{const product=productMap.get(id);return `• ${product.name} × ${count} — ${formatPrice(product.price*count)}`;});const total=Object.entries(cart).reduce((sum,[id,count])=>sum+productMap.get(id).price*count,0);return{lines,total};}
function openCheckout(){const{lines,total}=cartSummary();document.querySelector("#order-preview").innerHTML=`${lines.join("<br>")}<br><br><b>Разом: ${formatPrice(total)}</b>`;closeCart();checkoutDialog.showModal();}
function buildOrder(form){const{lines,total}=cartSummary(),data=new FormData(form);return["Нове замовлення ХАТА.ON","",...lines,`Разом: ${formatPrice(total)}`,"",`Ім’я: ${data.get("name")}`,`Телефон: ${data.get("phone")}`,`Доставка: ${data.get("delivery")}`,data.get("comment")?`Коментар: ${data.get("comment")}`:"","","Прошу підтвердити наявність і фінальну суму."].filter(Boolean).join("\n");}
async function copyOrder(){try{await navigator.clipboard.writeText(preparedOrder);document.querySelector("#copy-status").textContent="Текст скопійовано ✓";}catch{document.querySelector("#copy-status").textContent="Не вдалося скопіювати — скористайтеся кнопкою «Поділитися».";}}
async function shareOrder(){const telegram=window.HATA_ON_CONFIG?.telegram?.replace(/^@/,"").trim();if(telegram){window.open(`https://t.me/${telegram}?text=${encodeURIComponent(preparedOrder)}`,"_blank","noopener,noreferrer");return;}if(navigator.share){try{await navigator.share({title:"Замовлення ХАТА.ON",text:preparedOrder});return;}catch(error){if(error.name==="AbortError")return;}}await copyOrder();}
function openStoreContact(){const config=window.HATA_ON_CONFIG||{},telegram=config.telegram?.replace(/^@/,"").trim();if(telegram)return window.open(`https://t.me/${telegram}`,"_blank","noopener,noreferrer");if(config.phone)return window.location.href=`tel:${config.phone}`;if(config.email)return window.location.href=`mailto:${config.email}`;showToast("Надішліть контакт магазину — ми підключимо його тут");}
document.addEventListener("click",event=>{const add=event.target.closest("[data-add-product]");if(add)addToCart(add.dataset.addProduct);const change=event.target.closest("[data-cart-change]");if(change)updateQuantity(change.dataset.productId,Number(change.dataset.cartChange));const remove=event.target.closest("[data-remove-product]");if(remove){delete cart[remove.dataset.removeProduct];saveCart();renderCart();}});
document.querySelector("#open-cart").addEventListener("click",openCart);document.querySelector("#close-cart").addEventListener("click",closeCart);drawerBackdrop.addEventListener("click",closeCart);document.querySelector("#checkout-button").addEventListener("click",openCheckout);document.querySelector("#checkout-form").addEventListener("submit",event=>{event.preventDefault();if(!event.currentTarget.reportValidity())return;preparedOrder=buildOrder(event.currentTarget);checkoutDialog.close();resultDialog.showModal();});document.querySelector("#result-close").addEventListener("click",()=>resultDialog.close());document.querySelector("#share-order").addEventListener("click",shareOrder);document.querySelector("#copy-order").addEventListener("click",copyOrder);document.querySelector("#contact-button").addEventListener("click",openStoreContact);document.querySelector("#footer-contact-cta").addEventListener("click",openStoreContact);document.addEventListener("keydown",event=>{if(event.key==="Escape"&&cartDrawer.classList.contains("open"))closeCart();});document.querySelector("#year").textContent=new Date().getFullYear();renderProducts();renderCart();

